<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 


</head>
<body>


	<form action="../administrador/pages/agregar.php" method="POST"> 
	<div class="content">
	<h1>Usuario</h1>
	<hr>
	<label>Usuario</label>
	<input type="text" >
<hr>
	<label>Contraseña</label> 
	<input type="number"> 


	<button>REGISTRAR</button>


<hr>
<a  href="http://localhost/estudiantes/administrador/pages/agregar.php">¿No tiene una cuenta?</a>
	</form>	





<style>
	
	h1
	{
color: darkmagenta;

text-align: center;

}
.content
{

	 color: darkmagenta;;
	border: solid;
	text-align: center; 
	border-color: black;

} 
form{
	background-color:beige  ;
}
button{
	color: darkmagenta;
	background:grey ;
}


</style>

</div>
</body>
</html>